### ISSUE TITLE
[bug] CORS policy block preflight request

### ISSUE THREAD

**Issue by aveblackmetalstudio** [YetiForceCompany/YetiForceCRM#14569]
# 🐞 bug report

### ⁉️ Describe the bug

CORS policy block preflight requests

![image](https://user-images.githubusercontent.com/26859846/115349046-a686c480-a1b3-11eb-9d7a-e49f33c30c90.png)

### 🔥 How to trigger the error

Execute in browser console next code:

```
await fetch("https://gitstable.yetiforce.com/webservice/Users/Login", {
    "credentials": "omit",
    "headers": {
        "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
        "Upgrade-Insecure-Requests": "1"
    },
    "method": "OPTIONS",
    "mode": "cors"
});
```

### 👍 Expected Behavior
HTTP status **200 OK** on **OPTIONS** reqest
### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by z0lo13** [comment]
@aveblackmetalstudio what is the reason you are calling the login page from console?

**Comment by aveblackmetalstudio** [comment]
> @aveblackmetalstudio what is the reason you are calling the login page from console?

To prove that preflight request doesn't work

**Comment by z0lo13** [comment]
@aveblackmetalstudio 
![image](https://user-images.githubusercontent.com/23143958/117898232-828a4080-b292-11eb-8797-4efd44e8019e.png)

**Comment by z0lo13** [comment]
@aveblackmetalstudio 
![image](https://user-images.githubusercontent.com/23143958/117898416-edd41280-b292-11eb-8c15-b3f7f18d3dab.png)
it does give me an error as well but with a different code.

**Comment by aveblackmetalstudio** [comment]
> @aveblackmetalstudio
> ![image](https://user-images.githubusercontent.com/23143958/117898416-edd41280-b292-11eb-8c15-b3f7f18d3dab.png)
> it does give me an error as well but with a different code.

Probably you has disabled webservice in config/Api.php

**Comment by mariuszkrzaczkowski** [comment]
I did a test in Postman, it works

What is the main reason for reporting a bug, because I don't really understand why you want it.

```
OPTIONS /webservice/Users/Login HTTP/1.1
X-API-KEY: VMUwfBydHSq1bsW485ikfvcC97P6gJsz
Content-Type: application/json
Authorization: Basic vG9ydbFnOnBvcnRhbA==
User-Agent: PostmanRuntime/7.28.0
Accept: */*
Cache-Control: no-cache
Host: gitstable.yetiforce.com
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 131
 
{
    "userName": "customer@yetiforce.com",
    "password": "customer",
    "params": { 
        "language" : "en-US"
    }
}
```

```
HTTP/1.1 200 OK
Date: Wed, 12 May 2021 05:26:30 GMT
Server: Apache/2
access-control-allow-origin: *
access-control-allow-methods: POST
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization, x-api-key, x-encrypted, x-token
encrypted: 0
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: no-referrer
Expect-CT: enforce; max-age=3600
X-Robots-Tag: none
Cache-Control: private, no-cache, no-store, must-revalidate, post-check=0, pre-check=0
Upgrade: h2,h2c
Connection: Upgrade, Keep-Alive
Vary: User-Agent
Content-Length: 0
Keep-Alive: timeout=2, max=100
Content-Type: text/html; charset=UTF-8
```

**Comment by mariuszkrzaczkowski** [comment]
It works when you add an Authorization header
![image](https://user-images.githubusercontent.com/10198654/117924317-d5491400-b2f5-11eb-8d94-80452e1a9bef.png)

**Comment by aveblackmetalstudio** [comment]
> I did a test in Postman, it works
> 
> What is the main reason for reporting a bug, because I don't really understand why you want it.
> 
> ```
> OPTIONS /webservice/Users/Login HTTP/1.1
> X-API-KEY: VMUwfBydHSq1bsW485ikfvcC97P6gJsz
> Content-Type: application/json
> Authorization: Basic vG9ydbFnOnBvcnRhbA==
> User-Agent: PostmanRuntime/7.28.0
> Accept: */*
> Cache-Control: no-cache
> Host: gitstable.yetiforce.com
> Accept-Encoding: gzip, deflate, br
> Connection: keep-alive
> Content-Length: 131
>  
> {
>     "userName": "customer@yetiforce.com",
>     "password": "customer",
>     "params": { 
>         "language" : "en-US"
>     }
> }
> ```
> 
> ```
> HTTP/1.1 200 OK
> Date: Wed, 12 May 2021 05:26:30 GMT
> Server: Apache/2
> access-control-allow-origin: *
> access-control-allow-methods: POST
> access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization, x-api-key, x-encrypted, x-token
> encrypted: 0
> X-XSS-Protection: 1; mode=block
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Frame-Options: SAMEORIGIN
> X-Content-Type-Options: nosniff
> X-Permitted-Cross-Domain-Policies: none
> Referrer-Policy: no-referrer
> Expect-CT: enforce; max-age=3600
> X-Robots-Tag: none
> Cache-Control: private, no-cache, no-store, must-revalidate, post-check=0, pre-check=0
> Upgrade: h2,h2c
> Connection: Upgrade, Keep-Alive
> Vary: User-Agent
> Content-Length: 0
> Keep-Alive: timeout=2, max=100
> Content-Type: text/html; charset=UTF-8
> ```

It works in postman, because postman doesn't check cors policy. In response you received header **access-control-allow-methods: POST**.

The reason is because frontend developers have problem with this. For example in PWA application.

**Comment by mariuszkrzaczkowski** [comment]
For your example, I have this headline too 
![image](https://user-images.githubusercontent.com/10198654/117925840-1a6e4580-b2f8-11eb-947a-47b02d7635ec.png)

![image](https://user-images.githubusercontent.com/10198654/117925832-17735500-b2f8-11eb-84f9-187058c58f9e.png)

**Comment by aveblackmetalstudio** [comment]
@mariuszkrzaczkowski [What is preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request)

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/5087e64b7790a4c96a2887d192b87d16d261552f

**Comment by aveblackmetalstudio** [comment]
@mariuszkrzaczkowski 

> Fixed [5087e64](https://github.com/YetiForceCompany/YetiForceCRM/commit/5087e64b7790a4c96a2887d192b87d16d261552f)

Still not works
![image](https://user-images.githubusercontent.com/26859846/117979253-fed46080-b332-11eb-93b3-ec38bab17a2e.png)
