### ISSUE TITLE
[bug] portal demo credentials not working

### ISSUE THREAD

**Issue by rulotec** [YetiForceCompany/YetiForceCRM#14740]
Portal Demo credentials not working:

https://gitdeveloper.yetiforce.com/portal/

![image](https://user-images.githubusercontent.com/36896420/120033133-c97d7300-bfc0-11eb-8366-26b0a518c045.png)

customer/customer
vendor/vendor

are not valid

same applies here: https://gitdevportal.yetiforce.com/

**Comment by mariuszkrzaczkowski** [comment]
Fixed, there are currently quite a few changes to portal 2 and the crm API, so there may be temporary performance issues.

**Comment by apcloic** [comment]
@mariuszkrzaczkowski 
FYI, portal demo credentials still not working.
Regards,

**Comment by kassimg12** [comment]
Hello, yetiforce families

is there a free version of yetiforce portal?
I found a web service standard documentation at https://doc.yetiforce.com/api/#/
is it possible to use it for customer portal here https://github.com/YetiForceCompany/YetiForcePortal2

Thank you!
