### ISSUE TITLE
version 2.3 new installation fails with ERR_NOT_AUTHORIZED_TO_PERFORM_THE_OPERATION

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#2031]
ERR_NOT_AUTHORIZED_TO_PERFORM_THE_OPERATION is the error I get at the start of the installation.

Do you know why that would be

**Comment by jbmcclain** [comment]
I get the same issues

**Comment by amicheals** [comment]
I turned on display errors and tried to do the installation again.

This is what I received

Warning: session_start(): open(/cache/session/sess_a7m092a9g7iknogc1ditfohib3, O_RDWR) failed: No such file or directory (2) in /var/www/html/rm/libraries/csrf-magic/csrf-magic.php on line 392

Installation Wizard
ERR_NOT_AUTHORIZED_TO_PERFORM_THE_OPERATION
Warning: Unknown: open(/cache/session/sess_a7m092a9g7iknogc1ditfohib3, O_RDWR) failed: No such file or directory (2) in Unknown on line 0

Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/cache/session) in Unknown on line 0

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/99031960aa63782cced3c173ee5c04f292bd77ee

**Comment by jbmcclain** [comment]
awesome response time! But I still have the same issue.  I have even tried this as a new install on a new test vm

**Comment by bpabiszczak** [comment]
We will publish today patche [install zip]

**Comment by jbmcclain** [comment]
Awesome! you guys are great!

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/UpdatePackages/tree/master/YetiForce%20CRM%202.x.x/2.3.0_to_2.4.0/zip

**Comment by ajl-ewp** [comment]
I just got this error on 4.4.0 install? Any tips
