### ISSUE TITLE
outgoing mail

### ISSUE THREAD

**Issue by jbmcclain** [YetiForceCompany/YetiForceCRM#2293]
I have the smtp server configured correctly and received a notification email.  but to send notifications out do i need to configure the mail client.  All i am wanting todo is send notifications to specific emails using the work flow

**Comment by nikdejan** [comment]
You do not need Mail Client for that. SMTP configuration is enough.

**Comment by jbmcclain** [comment]
Thanks!

**Comment by jbmcclain** [comment]
just wondering if there is any hints or steps in making the workflow send out all notifications with the project module on changes. Ihave set up the workflow and template to send mail.  I am using server 2008 R2 with Xampp .  I am woundering if there is somthing withen the php that needs to be added.
Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.6.12

**Comment by jbmcclain** [comment]
any way to include tls protocol and not just ssl protocols?

**Comment by bpabiszczak** [comment]
https://www.google.pl/search?q=Xampp+tls+ssl&oq=Xampp+tls+ssl&aqs=chrome..69i57.3975j0j7&sourceid=chrome&es_sm=0&ie=UTF-8

**Comment by jbmcclain** [comment]
Thanks!

**Comment by jbmcclain** [comment]
how i fixed it if anyone else needs this.  if on a windows environment you need to got to the install directory \cron open the vtigercrom.bat and change the paths to the full paths of the directory structure..

set VTIGERCRM_ROOTDIR="C:\xampp\htdocs\"installdirectory"
set PHP_EXE="C:\xampp\php\php.exe"

**Comment by louiepelon** [comment]
In order to use Roundcube, do I need to setup a db separate from the yeticrm? I've put in all my information correctly but still cannot connect. The log (as mentioned above) is empty.
