### ISSUE TITLE
[Bug] Fatal Error on saving new Outsourced product

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2330]
Fatal error: Class 'Vtiger_sharedOwner_UIType' not found in /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Users/models/Privileges.php on line 244

**Comment by eptapsyxos** [comment]
Same  issue on contacts
Fatal error: Class 'Vtiger_sharedOwner_UIType' not found in /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Users/models/Privileges.php on line 244

**Comment by nikdejan** [comment]
Same on Products and Assets.

**Comment by florek41** [comment]
+Leads

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/6461bd441ce4a984820e407e7ec8ebe97df87d93

**Comment by nikdejan** [comment]
Still not working for outsourced product. The error is different.
Error!!!
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yetiforce1_dev.vtiger__showners' doesn't exist

#0 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/include/database/PearDatabase.php(339): PDO->prepare('SELECT DISTINCT...')
#1 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/uitypes/SharedOwner.php(46): PearDatabase->pquery('SELECT DISTINCT...', Array)
#2 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/models/Field.php(108): Vtiger_SharedOwner_UIType->getDisplayValue('', false, false, false)
#3 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/cache/templates_c/vlayout/b6f3e091b1b22f73922d403418f6c97bad8c7ac6.file.DetailViewBlockView.tpl.php(183): Vtiger_Field_Model->getDisplayValue('')
#4 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/libraries/Smarty/libs/sysplugins/smarty_internal_templatebase.php(188): content_5656e3158f01c3_43680407(Object(Smarty_Internal_Template))
#5 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/libraries/Smarty/libs/sysplugins/smarty_internal_template.php(304): Smarty_Internal_TemplateBase->fetch(NULL, NULL, NULL, NULL, false, false, true)
#6 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/cache/templates_c/vlayout/f73e0fbdaddbbe49ba63977da86d07c3930a3440.file.DetailViewFullContents.tpl.php(29): Smarty_Internal_Template->getSubTemplate('modules/Vtiger/...', NULL, NULL, 0, NULL, Array, 0)
#7 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/libraries/Smarty/libs/sysplugins/smarty_internal_templatebase.php(188): content_5656e3157de0e3_96439028(Object(Smarty_Internal_Template))
#8 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/include/runtime/Viewer.php(191): Smarty_Internal_TemplateBase->fetch('modules/Vtiger/...')
#9 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/views/Detail.php(240): Vtiger_Viewer->view('DetailViewFullC...', 'OutsourcedProdu...', true)
#10 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/views/Detail.php(169): Vtiger_Detail_View->showModuleDetailView(Object(Vtiger_Request))
#11 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/include/main/WebUI.php(225): Vtiger_Detail_View->process(Object(Vtiger_Request))
#12 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/index.php(25): Vtiger_WebUI->process(Object(Vtiger_Request))
#13 {main}

**Comment by nikdejan** [comment]
Similar for Price Book
