### ISSUE TITLE
Error updating from version 3.4 to 4.0

### ISSUE THREAD

**Issue by cosmibota** [YetiForceCompany/YetiForceCRM#4264]
I get this error udating from version 3.4.1427 to 4.0.0

_"Notice: Use of undefined constant ROOT_DIRECTORY - assumed 'ROOT_DIRECTORY' in /var/www/html/crmsign/include/ConfigUtils.php on line 165
Fatal error: Uncaught Error: Call to a member function addField() on boolean in /var/www/html/crmsign/cache/updates/init2.php:713 Stack trace: #0 /var/www/html/crmsign/cache/updates/init2.php(1114): YetiForceUpdate2->setFields(Array) #1 /var/www/html/crmsign/cache/updates/init2.php(214): YetiForceUpdate2->updateData() #2 /var/www/html/crmsign/cache/updates/init2.php(6): YetiForceUpdate2->update() #3 {main} thrown in /var/www/html/crmsign/cache/updates/init2.php on line 713"_

* YetiForce Version used: 3.4.1427
* Browser name and version: Chrome
* Environment name and version: Ubuntu 16.04, PHP 7.0.16, Mysql 14.14
* Operating System and version:

**Comment by migoi** [comment]
the missing ROOT_DIRECTORY Notice should be fixed in current code. I can remenber this one - there was two of them. One is caused by cron.

**Comment by mariuszkrzaczkowski** [comment]
I've added a fix, check 3.4.1427_to_4.0.0_v3.zip
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.0.0
https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%203.x.x/Update%20packages/

**Comment by StaggerLeee** [comment]
I still cannot update. Changed back to PHP version that worked last time for update, and same problem.
I see all mandatory on list is done in my server.

Is there any way to upgrade to 4.x manually ?
