### ISSUE TITLE
System Setting MENU-  ISSUE

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4444]
#### Issue

![menu](https://cloud.githubusercontent.com/assets/3030997/26414622/231817ee-4086-11e7-930a-e441e6fe8eae.gif)

#### Expected Behavior

accesses to submenu

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.0.305 (dev)
* Browser name and version: chrome and firedox (latest stable)
* Environment name and version:
* Operating System and version:

**Comment by TomaszQr** [comment]
Fixed via https://github.com/YetiForceCompany/YetiForceCRM/commit/8922686033368ae42057cc471a5dfd6876594647

**Comment by skramanzia** [comment]
@TomaszQr occurred again in dev 4.0.332

**Comment by skramanzia** [comment]
@paula-w, @TomaszQr  Hi Team, the issue still in the current version 4.0.373.

**Comment by WalterLuis** [comment]
add this in public_html\layouts\basic\skins\style.min.css

	.ps-scrollbar-y-rail{display:none !important}.slimScrollBar{right: -7px !important}
