### ISSUE TITLE
[BUG] Mass edit users dont works v4.2.435

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5225]
v4.2.205

![1121](https://user-images.githubusercontent.com/19627226/30601213-9924b4c6-9d8b-11e7-9163-4189ce9ef35a.gif)

**Comment by ezbank** [comment]
Do not show save button v4.2.279

![error massedit users](https://user-images.githubusercontent.com/19627226/31110057-752ac44a-a82e-11e7-8e45-f3bf7536e940.gif)

**Comment by ezbank** [comment]
v4.2.435
![bug mass edit users](https://user-images.githubusercontent.com/19627226/32277101-f617813e-bf43-11e7-9535-95b79ba5f06d.gif)

**Comment by bpabiszczak** [comment]
Works in the latest version.

**Comment by ezbank** [comment]
it still exists V4.2.435

**Comment by bpabiszczak** [comment]
![maszz_edit](https://user-images.githubusercontent.com/10197525/32315745-ae806e7a-bfad-11e7-902d-8ce4e4e4fe3f.gif)

**Comment by ezbank** [comment]
I tested it, it only works at first. The next time, there will be an error

**Comment by mariuszkrzaczkowski** [comment]
The bug has been fixed already.

**Comment by ezbank** [comment]
it still exists v4.2.472
![zalo_screenshot_10_11_2017_1429291](https://user-images.githubusercontent.com/19627226/32662829-63f67dc4-c65e-11e7-936e-b048801b2ffb.png)
