### ISSUE TITLE
[BUG] v4.3 Do not display data when filtering by date 

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5903]
Do not display data when filtering by date
test on https://gitstable.yetiforce.com

![widget not show data](https://user-images.githubusercontent.com/19627226/34880164-28a158c4-f7e2-11e7-89ee-684c26c53625.gif)

**Comment by rskrzypczak** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/5c8e09fa81576317137f6057a4f5728e5610254c

**Comment by ezbank** [comment]
If you choose any one day, there are no results.
It only works when picking dates range.
Counters are also not refreshed

**Comment by waran70** [comment]
Updating related record still not working. Try update account picklist when modifying contact.
