### ISSUE TITLE
[gitdev v4.4.x] Wrong calculation in quotes

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#7630]
#### Issue

In "My Preferences" we use a "," as Decimal seperator and "." for the digit grouping seperator. Now we have the problem, that when we add a service "Consulting" in Days, then the price is calculated incorrectly when we add half days. With the standard Setting (look at screenshots) it works correctly!

#### Actual Behavior

![quote nok cust](https://user-images.githubusercontent.com/10259801/44020743-25902932-9ee3-11e8-9c24-7ac3e108cb4a.JPG)
![quote nok 1](https://user-images.githubusercontent.com/10259801/44020748-2a1334ae-9ee3-11e8-87a8-eca3f39fcab7.gif)

#### Expected Behavior

![quote ok cust](https://user-images.githubusercontent.com/10259801/44020753-2e8c76f8-9ee3-11e8-85ff-fcf47169ecb9.JPG)
![quote ok 1](https://user-images.githubusercontent.com/10259801/44020760-317ad31e-9ee3-11e8-9e48-902969acbb92.gif)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: gitdeveloper v 4.4.14 or new installation v4.4.0
* Browser name and version: chrome
* Environment name and version: WAMP / gitdeveloper
* Operating System and version: Windows 10

**Comment by SkavenKF** [comment]
I think this is a bug, look at the following video. The quantity change from value 1,5 to 1.5 when i save the quote and the price changes when i change from display to edit modus!
![bugyf](https://user-images.githubusercontent.com/10259801/47210979-a44e1000-d394-11e8-8ec9-5b33bf7c3775.gif)

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/0006fbc4d3566416acf2ff312de4f87b46f4b9a5 and https://github.com/YetiForceCompany/YetiForceCRM/commit/dd09978bbdae299be97f5e577299a7f03c981f52

**Comment by SkavenKF** [comment]
not fixed 😞

look at the video

1.     change the user parameters
2.     change a quote
3.     save with comma, it is correct
3.     display is also correct
4.     when i change, it changed from ',' to '.' and sum is not correct

![bugyf](https://user-images.githubusercontent.com/10259801/48847517-0dfd7780-eda2-11e8-907d-91c2f4f8ee3d.gif)
